image: openjdk:17-bullseye

stages:
    - build
    - test

build-script:
    stage: build
    before_script: 
    - apt update
    - apt install -y sudo
    - chmod u+x scripts/build.sh
    script: bash scripts/build.sh

test-script:
    stage: test
    before_script: 
    - apt update
    - apt install -y sudo
    - chmod u+x scripts/test.sh
    script: bash scripts/test.sh
