image: debian

stages:
    - build
    - test

build-script:
    stage: build
    pre_script: chmod u+x scripts/build.sh
    script: bash scripts/build.sh

test-script:
    stage: test
    pre_script: chmod u+x scripts/test.sh
    script: bash scripts/test.sh
