image: openjdk:17-bullseye

stages:
    - build
    - test

build-script:
    stage: build
    before_script: 
    - apt update && apt install -y sudo file
    script: bash scripts/build.sh

test-script:
    stage: test
    before_script: 
    - apt update && apt install -y sudo file
    script: bash scripts/test.sh
